-- 新增 customers 表
CREATE TABLE IF NOT EXISTS customers (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  country VARCHAR(50),
  contact VARCHAR(100),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 新增 admins 表
CREATE TABLE IF NOT EXISTS admins (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(256) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 扩展 qr_codes
ALTER TABLE qr_codes ADD COLUMN customer_id BIGINT UNSIGNED;

-- 扩展 name_records
ALTER TABLE name_records ADD COLUMN survey_answers JSON;
ALTER TABLE name_records ADD COLUMN team1 VARCHAR(50);
ALTER TABLE name_records ADD COLUMN team2 VARCHAR(50);
ALTER TABLE name_records ADD COLUMN team3 VARCHAR(50);
ALTER TABLE name_records ADD COLUMN team4 VARCHAR(50);
